'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'
import { api, ApiError } from '@/lib/api'
import { useToast } from '@/components/Toast'
import { Button, Card, Field, Input, Textarea, Select } from '@/components/ui'
import type { Unit } from '@/lib/types'

const UNITS: Unit[] = ['KG', 'QUINTAL', 'TON', 'BAG', 'CRATE', 'DOZEN']

const CATEGORIES = [
  { id: 'Vegetables', label: 'Vegetables', icon: '🥦', color: 'bg-emerald-50 text-emerald-600 border-emerald-200' },
  { id: 'Fruits', label: 'Fruits', icon: '🍎', color: 'bg-red-50 text-red-600 border-red-200' },
  { id: 'Grains', label: 'Grains', icon: '🌾', color: 'bg-amber-50 text-amber-600 border-amber-200' },
  { id: 'Pulses', label: 'Pulses', icon: '🫘', color: 'bg-yellow-50 text-yellow-700 border-yellow-200' },
  { id: 'Spices', label: 'Spices', icon: '🌶️', color: 'bg-orange-50 text-orange-600 border-orange-200' },
  { id: 'Dairy', label: 'Dairy', icon: '🥛', color: 'bg-blue-50 text-blue-600 border-blue-200' },
  { id: 'Organic', label: 'Organic', icon: '🌱', color: 'bg-green-50 text-green-700 border-green-200' },
  { id: 'Other', label: 'Other', icon: '📦', color: 'bg-slate-50 text-slate-600 border-slate-200' },
]

export default function NewListingPage() {
  const router = useRouter()
  const { show } = useToast()
  const [loading, setLoading] = useState(false)
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({})
  const [selectedCategory, setSelectedCategory] = useState('Vegetables')
  const [form, setForm] = useState({
    cropType: '',
    variety: '',
    quantity: '',
    unit: 'KG' as Unit,
    expectedPrice: '',
    harvestDate: '',
    description: '',
  })

  const currentCatObj = CATEGORIES.find(c => c.id === selectedCategory) || CATEGORIES[0]

  const set = (k: keyof typeof form) => (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
  ) => setForm((f) => ({ ...f, [k]: e.target.value }))

  const submit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    setFieldErrors({})
    try {
      await api.post('/farmer/listings', {
        cropType: form.cropType || selectedCategory,
        variety: form.variety || undefined,
        quantity: Number(form.quantity),
        unit: form.unit,
        expectedPrice: Number(form.expectedPrice),
        harvestDate: form.harvestDate,
        description: form.description || undefined,
      })
      show('success', 'Listing created')
      router.push('/farmer/listings')
    } catch (err) {
      if (err instanceof ApiError && err.fields) {
        setFieldErrors(Object.fromEntries(err.fields.map((f) => [f.field, f.message])))
      }
      show('error', err instanceof ApiError ? err.message : 'Could not create listing')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <Link href="/farmer/listings" className="inline-flex items-center gap-1.5 text-sm text-muted hover:text-ink">
        <ArrowLeft className="h-4 w-4" />
        Back to listings
      </Link>
      <div>
        <h1 className="font-display text-3xl font-semibold text-ink">New Harvest Listing</h1>
        <p className="text-sm text-muted">Select category, view auto-generated icon preview, and set your price.</p>
      </div>

      {/* Category Selection Card with Dynamic Icon Preview (Image 2 style) */}
      <Card className="p-5 border-emerald-100 bg-gradient-to-br from-emerald-50/50 to-white">
        <div className="flex items-center gap-4 mb-4 pb-4 border-b border-emerald-100">
          <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-white shadow-md text-3xl border border-emerald-100">
            {currentCatObj.icon}
          </div>
          <div>
            <span className="text-xs font-semibold uppercase tracking-wider text-emerald-700">Autogenerated Icon Preview</span>
            <h3 className="font-display text-lg font-bold text-ink">{form.cropType || currentCatObj.label}</h3>
            <p className="text-xs text-muted">Customers & Brokers will see this icon on your harvest listing card.</p>
          </div>
        </div>

        <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-3">Select Category</p>
        <div className="grid grid-cols-4 gap-2 sm:grid-cols-4">
          {CATEGORIES.map((c) => (
            <button
              key={c.id}
              type="button"
              onClick={() => {
                setSelectedCategory(c.id)
                if (!form.cropType || CATEGORIES.some(cat => cat.id === form.cropType)) {
                  setForm(f => ({ ...f, cropType: c.id }))
                }
              }}
              className={`flex flex-col items-center justify-center p-3 rounded-xl border transition-all ${
                selectedCategory === c.id
                  ? 'border-emerald-600 bg-white shadow-md ring-2 ring-emerald-500/20 scale-105'
                  : 'border-slate-200 bg-white/70 hover:bg-white hover:border-slate-300'
              }`}
            >
              <span className="text-2xl mb-1">{c.icon}</span>
              <span className="text-xs font-semibold text-slate-700">{c.label}</span>
            </button>
          ))}
        </div>
      </Card>

      <Card className="p-6">
        <form onSubmit={submit} className="space-y-5">
          <div className="grid gap-4 sm:grid-cols-2">
            <Field label="Crop / Produce Name" error={fieldErrors.cropType}>
              <Input required value={form.cropType} onChange={set('cropType')} placeholder="e.g. Thompson Seedless Grapes" />
            </Field>
            <Field label="Variety" hint="Optional">
              <Input value={form.variety} onChange={set('variety')} placeholder="Export Grade / Organic" />
            </Field>
          </div>

          <div className="grid gap-4 sm:grid-cols-3">
            <Field label="Quantity" error={fieldErrors.quantity}>
              <Input type="number" min="1" step="any" required value={form.quantity} onChange={set('quantity')} placeholder="500" />
            </Field>
            <Field label="Unit">
              <Select value={form.unit} onChange={set('unit')}>
                {UNITS.map((u) => (
                  <option key={u} value={u}>
                    {u}
                  </option>
                ))}
              </Select>
            </Field>
            <Field label="Expected Price per Unit (₹)" error={fieldErrors.expectedPrice}>
              <Input type="number" min="1" step="any" required value={form.expectedPrice} onChange={set('expectedPrice')} placeholder="80" />
            </Field>
          </div>

          <Field label="Harvest Date" error={fieldErrors.harvestDate}>
            <Input type="date" required value={form.harvestDate} onChange={set('harvestDate')} />
          </Field>

          <Field label="Description" hint="Optional — quality, grade, pickup notes">
            <Textarea value={form.description} onChange={set('description')} placeholder="Export-grade, hand-picked from Nashik vineyard..." />
          </Field>

          <div className="flex gap-3">
            <Button type="submit" loading={loading} className="bg-emerald-700 hover:bg-emerald-800">
              Publish Listing
            </Button>
            <Link href="/farmer/listings">
              <Button type="button" variant="secondary">
                Cancel
              </Button>
            </Link>
          </div>
        </form>
      </Card>
    </div>
  )
}
