'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'
import { api, ApiError } from '@/lib/api'
import { useToast } from '@/components/Toast'
import { Button, Card, Field, Input, Textarea, Select } from '@/components/ui'

const CATEGORY_ITEMS = [
  { id: 'DAP', label: 'DAP', icon: '🧪' },
  { id: 'UREA', label: 'Urea', icon: '💧' },
  { id: 'NPK', label: 'NPK', icon: '🌿' },
  { id: 'MOP', label: 'MOP', icon: '💎' },
  { id: 'MICRONUTRIENT', label: 'Micro', icon: '🧬' },
  { id: 'PESTICIDE', label: 'Pesticide', icon: '🛡️' },
  { id: 'FUNGICIDE', label: 'Fungicide', icon: '🍄' },
  { id: 'SEED', label: 'Seeds', icon: '🌱' },
  { id: 'OTHER', label: 'Other', icon: '📦' },
]

const UNITS = ['BAG', 'KG', 'LITER', 'PIECE', 'TON']

export default function NewProductPage() {
  const router = useRouter()
  const { show } = useToast()
  const [loading, setLoading] = useState(false)
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({})
  const [form, setForm] = useState({
    name: '', brand: '', category: 'DAP', description: '',
    unit: 'BAG', price: '', initialStock: '', imageUrl: '',
  })

  const currentCatObj = CATEGORY_ITEMS.find(c => c.id === form.category) || CATEGORY_ITEMS[0]

  const set = (k: keyof typeof form) =>
    (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) =>
      setForm(f => ({ ...f, [k]: e.target.value }))

  const submit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true); setFieldErrors({})
    try {
      await api.post('/seller/products', {
        name: form.name, brand: form.brand || undefined, category: form.category,
        description: form.description || undefined, unit: form.unit,
        price: Number(form.price), initialStock: Number(form.initialStock) || 0,
        images: form.imageUrl ? [form.imageUrl] : [],
      })
      show('success', 'Product added to fertilizer catalog with product icon & photo')
      router.push('/seller/products')
    } catch (err) {
      if (err instanceof ApiError && err.fields)
        setFieldErrors(Object.fromEntries(err.fields.map(f => [f.field, f.message])))
      show('error', err instanceof ApiError ? err.message : 'Could not add product')
    } finally { setLoading(false) }
  }

  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <Link href="/seller/products" className="inline-flex items-center gap-1.5 text-sm text-muted hover:text-ink">
        <ArrowLeft className="h-4 w-4" />Back to inventory
      </Link>
      <div>
        <h1 className="font-display text-3xl font-semibold text-ink">Add Fertilizer / Agro Product</h1>
        <p className="text-sm text-muted">List supplies visible exclusively to farmers & agricultural buyers.</p>
      </div>

      {/* Category Selection Card with Dynamic Icon Preview (Image 2 style) */}
      <Card className="p-5 border-emerald-100 bg-gradient-to-br from-emerald-50/50 to-white">
        <div className="flex items-center gap-4 mb-4 pb-4 border-b border-emerald-100">
          <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-white shadow-md text-3xl border border-emerald-100">
            {currentCatObj.icon}
          </div>
          <div>
            <span className="text-xs font-semibold uppercase tracking-wider text-emerald-700">Autogenerated Icon Preview</span>
            <h3 className="font-display text-lg font-bold text-ink">{form.name || currentCatObj.label}</h3>
            <p className="text-xs text-muted">Farmers looking for fertilizers will see this category icon.</p>
          </div>
        </div>

        <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-3">Select Fertilizer Category</p>
        <div className="grid grid-cols-3 gap-2 sm:grid-cols-5">
          {CATEGORY_ITEMS.map((c) => (
            <button
              key={c.id}
              type="button"
              onClick={() => setForm(f => ({ ...f, category: c.id }))}
              className={`flex flex-col items-center justify-center p-3 rounded-xl border transition-all ${
                form.category === c.id
                  ? 'border-emerald-600 bg-white shadow-md ring-2 ring-emerald-500/20 scale-105'
                  : 'border-slate-200 bg-white/70 hover:bg-white hover:border-slate-300'
              }`}
            >
              <span className="text-2xl mb-1">{c.icon}</span>
              <span className="text-xs font-semibold text-slate-700">{c.label}</span>
            </button>
          ))}
        </div>
      </Card>

      <Card className="p-6">
        <form onSubmit={submit} className="space-y-5">
          <div className="grid gap-4 sm:grid-cols-2">
            <Field label="Product Name" error={fieldErrors.name}>
              <Input required value={form.name} onChange={set('name')} placeholder="e.g. IFFCO DAP 18-46-0" />
            </Field>
            <Field label="Brand / Manufacturer" hint="Optional">
              <Input value={form.brand} onChange={set('brand')} placeholder="IFFCO / Coromandel" />
            </Field>
          </div>
          <div className="grid gap-4 sm:grid-cols-2">
            <Field label="Packaging Unit">
              <Select value={form.unit} onChange={set('unit')}>
                {UNITS.map(u => <option key={u} value={u}>{u}</option>)}
              </Select>
            </Field>
            <Field label="Initial Stock Quantity" hint="Available inventory count">
              <Input type="number" min="0" step="any" value={form.initialStock} onChange={set('initialStock')} placeholder="100" />
            </Field>
          </div>
          <div className="grid gap-4 sm:grid-cols-2">
            <Field label="Price per Unit (₹)" error={fieldErrors.price}>
              <Input type="number" min="1" step="any" required value={form.price} onChange={set('price')} placeholder="1350" />
            </Field>
            <Field label="Product Image URL / Photo Link" hint="Optional — or autogenerated from category">
              <Input value={form.imageUrl} onChange={set('imageUrl')} placeholder="https://images.unsplash.com/photo-..." />
            </Field>
          </div>
          <Field label="Composition & Technical Details" hint="Optional">
            <Textarea value={form.description} onChange={set('description')} placeholder="NPK ratio, application dosage per acre, organic certification info..." />
          </Field>
          <div className="flex gap-3">
            <Button type="submit" loading={loading} className="bg-emerald-700 hover:bg-emerald-800">Add Product</Button>
            <Link href="/seller/products"><Button type="button" variant="secondary">Cancel</Button></Link>
          </div>
        </form>
      </Card>
    </div>
  )
}
